baseURL = "https://chiefdennis.github.io"
title = "Chief Dennis' Blog"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 12
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Dennis Drebitca"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Chief Dennis' personal blog"
keywords = "blog,developer,personal,cybersecurity,IT,cloud"
info = ["Aerospace engineer", "Junior Cloud Security Engineer"]
avatarURL = "avatar.png"
#gravatar = ""
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["css/custom.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/chiefdennis/"

#[[params.social]]
#name = "Twitter"
#icon = "fa fa-2x fa-twitter"
#weight = 2
#url = ""

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/dennis-gabriel-drebitca-popovici-8731b4233/"

#[[params.social]]
#name = "RSS"
#icon = "fa fa-2x fa-rss"
#weight = 4
#url = "https://myhugosite.com/index.xml"
#rel = "alternate"
#type = "application/rss+xml"

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Catch The Flag"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Tags"
weight = 4
url = "tags/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

#[languages.es-es]
#languageName = "Español"
#title = "El blog de Dennis"

#[languages.es-es.params]
#author = "Dennis Gabriel"
#info = ["Ingeniero aeroespacial", "Ingeniero de seguridad cloud junior"]
#description = "Blog personal de Dennis"
#keywords = "IT,ciberseguridad,cloud"

#[[languages.es-es.menu.main]]
#name = "Sobre mi"
#weight = 1
#url = "about/"

#[[languages.es-es.menu.main]]
#name = "Máquinas HTB"
#weight = 2
#url = "posts/"

#[[languages.es-es.menu.main]]
#name = "Proyectos"
#weight = 3
#url = "projects/"

#[[languages.es-es.menu.main]]
#name = "Contacto"
#weight = 4
#url = "contact/"